# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f732283297f5512940696d047c34ebbd7b8ba833b3c17f18578dee8c03c627ec104d8651fc3e5d66deccec122dd860f446c0c96a21b0b669162c22578965c8b

test:
  secret_key_base: 941c7b42013d9f91edde4db7e5216168e9dd056ce1e3c8a3556dede524fbb7a7234a463f3e58459c723d5ce3860025aebe607a7ddde0aaac92f79bad1ae07862

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
